trollicons_icons = [ // global namespaces ftw!
{ key: 'actuallyok', icon: 'Actually-actually-okay3.png' },
{ key: 'aintthatsomeshit', icon: 'Aint That Some Shit-celo-aintthatsomeshit.png' },
{ key: 'aliens', icon: 'Aliens-aliens.png' },
{ key: 'allthethings', icon: 'All the things-allthethings.png' },
{ key: 'aintjoke', icon: 'Anti Joke Chicken-antichicken-antijokechicken.png' },
{ key: 'areyoukidding', icon: 'Are You Kidding Me-areyoukiddingme-areyoukidding-stfu-areyoufuckingkiddingme.png' },
{ key: 'whyhands', icon: 'Aw Man-awman-whyhands.png' },
{ key: 'awwhy', icon: 'Aw-aw-why.png' },
{ key: 'awwyea', icon: 'Awww Yea-awyea-awyeah-ay.png' },
{ key: 'badpoker', icon: 'Bad Poker Face-badpokerface-badpoker.png' },
{ key: 'beerguy', icon: 'Beer Guy-beerguy-beer.png' },
{ key: 'behbeh', icon: 'Beh-beh.png' },
{ key: 'bigmouth', icon: 'Big Mouth High Face-bmhf-bigmouth.png' },
{ key: 'busted', icon: 'Busted-busted-oops.png' },
{ key: 'canadianrage', icon: 'Canadian Rage-canadianrage-canadian.png' },
{ key: 'captainobvious', icon: 'Captain Obvious-captainobvious.png' },
{ key: 'cerealangry', icon: 'Cereal Guy Angry-cerealguyangry-cerealangry.png' },
{ key: 'cerealsquint', icon: 'Cereal Guy Squint-cerealguysquint-cerealsquint.png' },
{ key: 'cerealguy', icon: 'Cereal Guy-cerealguy-cereal.png' },
{ key: 'cerealspit', icon: 'Cereal Spitting-cerealspit-spit.png' },
{ key: 'challengeconsidered', icon: 'Challenge Considered-challengeconsidered-considered.png' },
{ key: 'challenge', icon: 'Challenge-challenge.png' },
{ key: 'classyfap', icon: 'Classy Fap-classyfap-richfap.png' },
{ key: 'clevergirl', icon: 'Clever Girl-clevergirl.png' },
{ key: 'closeenough', icon: 'Close Enough-closeenough-ce.png' },
{ key: 'conflictingemotions', icon: 'Conflicting Emotions-notsure-dunno.png' },
{ key: 'confused', icon: 'Confused-confused-butwhy.png' },
{ key: 'crazyconcentrate', icon: 'Crazy Concentrate Sweat-sweat-workinghard.png' },
{ key: 'crycry', icon: 'Cry-cry-baw.png' },
{ key: 'dazed', icon: 'Dazed-dazed.png' },
{ key: 'deskflip', icon: 'Desk flip-deskflip-flip-tableflip-desk-table.png' },
{ key: 'deviltroll', icon: 'Devil Troll-deviltroll-evil-devil.png' },
{ key: 'dogsweetjesus', icon: 'Dog Sweet Jesus-dogsweetjesus.png' },
{ key: 'doge', icon: 'Doge-doge.png' },
{ key: 'douche', icon: 'Douchebag-dbag-brah-douche-douchebag.png' },
{ key: 'drool', icon: 'Drool-drool.png' },
{ key: 'drunk', icon: 'Drunk-drunk.png' },
{ key: 'dudecomeon', icon: 'Dude Come On Smile-comeon.png' },
{ key: 'dudedude', icon: 'Dude-dude-meh.png' },
{ key: 'dumbfounded', icon: 'Dumbfounded Kid-whoa-ooh.png' },
{ key: 'epicfail', icon: 'Epic Fail Guy-epicfailguy-efg.png' },
{ key: 'errg', icon: 'Errg-errg-release.png' },
{ key: 'wentbetter', icon: 'Everything Went Better Than Expected-everythingwentbetterthanexpected-betterthanexpected-ewbte.png' },
{ key: 'evilsmile', icon: 'Evil Smile-evilsmile-hah.png' },
{ key: 'excited', icon: 'Excited-ya-yey.png' },
{ key: 'eyeseyes', icon: 'Eyes-eyes-fff-imminent.png' },
{ key: 'faggotdog', icon: 'Faggot-Dog-faggotdog.png' },
{ key: 'fapfapfap', icon: 'Fap Fap-fap-fapfap-fapfapfap.png' },
{ key: 'feellikeasir', icon: 'Feel Like A Sir-likeasir.png' },
{ key: 'femalefap', icon: 'Female Fap-femalefap-schlick.png' },
{ key: 'foreveraloneexcited', icon: 'Forever Alone Excited-foreveraloneexcited-faexcited-falaugh-friends.png' },
{ key: 'foreveralone', icon: 'Forever Alone-foreveralone-fa.png' },
{ key: 'foulbachelor', icon: 'Foul Bachelor Frog-bachelorfrog-foulbachelorfrog-malefrog.png' },
{ key: 'foulbachelorette', icon: 'Foul Bachelorette Frog-bachelorettefrog-foulbachelorettefrog-femalefrog.png' },
{ key: 'freddie', icon: 'Freddie Mercury-freddie-hellyes.png' },
{ key: 'frynotsureif', icon: 'Fry Not Sure If-notsureif.png' },
{ key: 'frynotsureiftrolling', icon: 'Fry-fry-notsureiftrolling-nsit.png' },
{ key: 'fumanchu', icon: 'Fu Manchu-fumanchu.png' },
{ key: 'fuckthatshitright', icon: 'Fuck That Shit Right-rightfuckthat-rft.png' },
{ key: 'fuckthatshit', icon: 'Fuck That Shit-fuckthatshit-fuckthat-ft-leftfuckthat-lft.png' },
{ key: 'fuckyeahwords', icon: 'Fuck Yeah Words-fuckyeahwords-fywords.png' },
{ key: 'fuckyeah', icon: 'Fuck Yeah-fuckyeah-fy.png' },
{ key: 'fuu', icon: 'Fuu-rage2-epicrage-fu2.png' },
{ key: 'gtfo', icon: 'GTFO-gtfo.png' },
{ key: 'gah', icon: 'Gah-gah-sweaty.png' },
{ key: 'gasp', icon: 'Gasp-gasp.png' },
{ key: 'gaytroll', icon: 'Gay Troll-gaytroll-gay.png' },
{ key: 'genius', icon: 'Genius-genius-genious.png' },
{ key: 'gonnafuck', icon: 'Gonna fuck that taco-taco.png' },
{ key: 'grandmashit', icon: 'Grandma Shit-grandmashit-shit.png' },
{ key: 'grandma', icon: 'Grandma-grandma-granny.png' },
{ key: 'grannytroll', icon: 'Granny Troll-grannytroll.png' },
{ key: 'grinch', icon: 'Grinch-grinch.png' },
{ key: 'gropaga', icon: 'Gropaga-gropaga.png' },
{ key: 'grumpycat', icon: 'Grumpy Cat-grumpycat-grumpycatno.png' },
{ key: 'gunleft', icon: 'Gun Left-lgun.png' },
{ key: 'gunright', icon: 'Gun Right-rgun.png' },
{ key: 'happyface', icon: 'Happy Face -happyface.png' },
{ key: 'happy', icon: 'Happy-happy.png' },
{ key: 'haters', icon: 'Haters Gonna Hate-hatersgonnahate-haters-hgh.png' },
{ key: 'heh', icon: 'Heh heh-hehheh-hehehe.png' },
{ key: 'hehelizard', icon: 'Hehe Lizard-lizard.png' },
{ key: 'herp', icon: 'Herp Derp-herpderp-herp-derp.png' },
{ key: 'highexpectation', icon: 'High Expectation Asian Dad-asiandad.png' },
{ key: 'high', icon: 'High-high.png' },
{ key: 'hipsterkitty', icon: 'Hipster Kitty-hipster-hipsterkitty-hk.png' },
{ key: 'hmm', icon: 'Hmm-hmm.png' },
{ key: 'homophobic', icon: 'Homophobic Seal-seal-gayseal-gaay.png' },
{ key: 'iamdisappoint', icon: 'I Am Disappoint-son-disappoint.png' },
{ key: 'idontwanttolive', icon: 'I Dont Want to Live on This Planet Anymore-idontwannalive-farnsworth.png' },
{ key: 'ilied', icon: 'I Lied-ilied-wayevil.png' },
{ key: 'isee', icon: 'I See-isee-iseewhatyoudidthere.png' },
{ key: 'ifyouknowwhatimean', icon: 'If you know what i mean-ifyouknowwhatimean-bean.png' },
{ key: 'insanewolf', icon: 'Insane Wolf-insanewolf-wolf.png' },
{ key: 'itsnotokay', icon: 'It\'s Not Okay-itsnotokay-okay4.png' },
{ key: 'itssomething', icon: 'It\'s Something-itssomething.png' },
{ key: 'itstime', icon: 'It\'s Time-itstime-serious-determined.png' },
{ key: 'itsatrap', icon: 'It\'s a Trap-trap-itsatrap.png' },
{ key: 'lolnotext', icon: 'LOL (No Text)-ooo.png' },
{ key: 'lol', icon: 'LOL-lol-LOL.png' },
{ key: 'lamepun', icon: 'Lame Pun Coon-lamepuncoon-lamepun-puncoon.png' },
{ key: 'look', icon: 'Look-look.png' },
{ key: 'megustacreepy', icon: 'Me Gusta Mucho Creepy-creepymegusta-cmg-evilmegusta-emg.png' },
{ key: 'megustaperfect', icon: 'Me Gusta Perfect-mgperfect-megustaperfect-mgp.png' },
{ key: 'megusta', icon: 'Me Gusta-bepistrollingyoubetter-megusta-mg.png' },
{ key: 'melvinfuckyeah', icon: 'Melvin Fuck Yeah-melvinfuckyeah-melvinfy-mfy.png' },
{ key: 'melvin', icon: 'Melvin-melvin.png' },
{ key: 'milk', icon: 'Milk-milk.png' },
{ key: 'mom', icon: 'Mom-mom.png' },
{ key: 'moonshot', icon: 'Moonshot-moonshot-noway-shocked.png' },
{ key: 'motherofgod', icon: 'Mother Of God-motherofgod.png' },
{ key: 'newspaperguytear', icon: 'Newspaper Guy Tear-newspaperguytear-newspapertear-tear.png' },
{ key: 'newspaperguy', icon: 'Newspaper Guy-newspaperguy-newspaper.png' },
{ key: 'nomegusta', icon: 'No Me Gusta-nmg-nomegusta.png' },
{ key: 'no', icon: 'No-no.png' },
{ key: 'notbad', icon: 'Not Bad Obama-notbadobama-notbad-obama.png' },
{ key: 'notokay', icon: 'Not Okay-notokay-bitter.png' },
{ key: 'nothingtodo', icon: 'Nothing to do here-rocket-jetpack.png' },
{ key: 'numb', icon: 'Numb-numb-fear-scared-depressed.png' },
{ key: 'occupied', icon: 'Occupied-working-busy-focus.png' },
{ key: 'ohgodright', icon: 'Oh God Right-rohgod-rgross-rwtf.png' },
{ key: 'ohgodwhy', icon: 'Oh God Why-ohgodwhy.png' },
{ key: 'ohgodgross', icon: 'Oh God-ohgod-gross-wtf-lgross-lwtf.png' },
{ key: 'ohno', icon: 'Oh No-uh-ohno.png' },
{ key: 'ohyes', icon: 'Ohhh Yes-ohyes.png' },
{ key: 'okok', icon: 'Ok-ok-nice-great-thumb-thumbs.png' },
{ key: 'ok', icon: 'Okay-okay.png' },
{ key: 'omgrun', icon: 'Omg Run-omgrun-run.png' },
{ key: 'overjoyed', icon: 'Overjoyed-overjoyed-nowords-daww.png' },
{ key: 'paranoid', icon: 'Paranoid Parrot-paranoid-parrot-paranoidparrot.png' },
{ key: 'perfect', icon: 'Perfect-perfect-biggrin.png' },
{ key: 'pfft2', icon: 'Pffttchhchhh-pft2-expectant.png' },
{ key: 'pfft', icon: 'Pft-pft-lulz.png' },
{ key: 'philosoraptor', icon: 'Philosoraptor-philosoraptor-raptor.png' },
{ key: 'picard', icon: 'Picard Facepalm-facepalm-picard.png' },
{ key: 'pickletime', icon: 'Pickle Time-pickletime-pickle.png' },
{ key: 'pig', icon: 'Pig-pig-pigrage.png' },
{ key: 'pirate', icon: 'Pirate-pirate.png' },
{ key: 'pokerfacethick', icon: 'Poker Face Thick-thickpokerface-thickpoker-guilty.png' },
{ key: 'pokerface', icon: 'Poker Face-pokerface-poker-pf.png' },
{ key: 'problemguy', icon: 'Problem Guy-problemguy-okaytroll.png' },
{ key: 'puke', icon: 'Puke Rainbows-pukerainbows-pukesrainbows-rainbows.png' },
{ key: 'rageblank', icon: 'Rage Blank-blankrage.png' },
{ key: 'rageclassic', icon: 'Rage Classic-fu-rage.png' },
{ key: 'rageextreme', icon: 'Rage Extreme-extremerage-xrage.png' },
{ key: 'ragehappy', icon: 'Rage Happy-happyrage-hrage.png' },
{ key: 'ragelion', icon: 'Rage Lion-ragelion.png' },
{ key: 'ragenuclear', icon: 'Rage Nuclear-nuclearrage-nrage-fu3.png' },
{ key: 'rageomega', icon: 'Rage Omega-omegarage-orage-fu4.png' },
{ key: 'ragequiet', icon: 'Rage Quiet-quietrage.png' },
{ key: 'retarddog', icon: 'Retard Dog-retarddog-dog.png' },
{ key: 'retardedgirl', icon: 'Retarded Girl-retardedgirl.png' },
{ key: 'rich', icon: 'Rich Fu-richfu-rich-quite.png' },
{ key: 'sadmelvin', icon: 'Sad Melvin-sadmelvin.png' },
{ key: 'sadshadow', icon: 'Sad Shadow-sadshadow-okay2.png' },
{ key: 'sadtroll', icon: 'Sad Troll-sadtroll.png' },
{ key: 'sad', icon: 'Sad-sad.png' },
{ key: 'satisfied', icon: 'Satisfied-satisfied-relief-ahh-ah.png' },
{ key: 'seriously', icon: 'Seriously Chan-jackie-chan.png' },
{ key: 'shaking', icon: 'Shaking-shaking.png' },
{ key: 'sidemouth', icon: 'Side Mouth-sidemouth-lefu.png' },
{ key: 'smile', icon: 'Smile-smile-catsmile.png' },
{ key: 'soclose', icon: 'So Close-soclose.png' },
{ key: 'sohardcore', icon: 'So hardcore-hardcore-sohardcore.png' },
{ key: 'sociallyawkwardpenguin', icon: 'Socially Awkward Penguin-penguin-awkwardpenguin-sociallyawkwardpenguin.png' },
{ key: 'sonmegusta', icon: 'Son Me Gusta-sonmegusta-smg.png' },
{ key: 'spiderman', icon: 'Spiderpman-subtle-nonchalant.png' },
{ key: 'stare', icon: 'Stare-stare.png' },
{ key: 'straight', icon: 'Straight-straight.png' },
{ key: 'successkid', icon: 'Success Kid-successkid-kid-success.png' },
{ key: 'surprised', icon: 'Surprised Wide Open Mouth-surprised3.png' },
{ key: 'sweetjesus', icon: 'Sweet Jesus Face-sweetjesus-sj.png' },
{ key: 'tada', icon: 'Tada left-ltada.png' },
{ key: 'tada', icon: 'Tada-tada-rtada.png' },
{ key: 'thatway', icon: 'That Way-thatway.png' },
{ key: 'thefuckfemale', icon: 'The Fuck Female-gthefuck-gtf.png' },
{ key: 'thefuck', icon: 'The Fuck-thefuck-tf.png' },
{ key: 'tmyk', icon: 'The-More-You-Know-tmyk.png' },
{ key: 'thingswentok', icon: 'ThingsWentOkay-thingswentokay-wentokay.png' },
{ key: 'throwup', icon: 'Throw Up In Mouth-throwupinmouth-throwup-fullmouth.png' },
{ key: 'tongue', icon: 'Tongue-tongue.png' },
{ key: 'trolldadjump', icon: 'Troll Dad Jump-trolldadjump-tdjump-tdj.png' },
{ key: 'trolldadmonocle', icon: 'Troll Dad Monocle-trolldadmonocle-trolldadm-tdm.png' },
{ key: 'trollgod', icon: 'Troll God-trollgod-god.png' },
{ key: 'trollhot', icon: 'Troll Hot-trollhot-hottroll-babe.png' },
{ key: 'trollinsane', icon: 'Troll Insane-insanetroll-insane-excited.png' },
{ key: 'trolllol', icon: 'Troll Lol-trolol-trollol-trolllol.png' },
{ key: 'trollpeek', icon: 'Troll peeking-peek-trollpeek.png' },
{ key: 'troll', icon: 'Troll-troll-problem-umad.png' },
{ key: 'trolldad', icon: 'TrollDad-trolldad.png' },
{ key: 'trollicons', icon: 'Trollicons-trollicons.png' },
{ key: 'truestory', icon: 'True Story-truestory.png' },
{ key: 'uhm', icon: 'Uhm-uhm-mad.png' },
{ key: 'wtf', icon: 'WTF is this shit-picardwtf-wtfisthisshit.png' },
{ key: 'wahwah', icon: 'Wah-wah-huh.png' },
{ key: 'wait', icon: 'Wait-wait-awno.png' },
{ key: 'wat', icon: 'Wat-wat-suspicious.png' },
{ key: 'watchout', icon: 'Watch out-badass-watchout-ndgt-neil.png' },
{ key: 'whathaveidone', icon: 'What Have I done -whathaveidone-whid.png' },
{ key: 'whathaveyoudone', icon: 'What Have You Done-whathaveyoudone-whyd-done.png' },
{ key: 'whatconcerned', icon: 'What-concerned.png' },
{ key: 'winwin', icon: 'Win-win-epicwin.png' },
{ key: 'wizard', icon: 'Wizard-Guy-wizard.png' },
{ key: 'yuno', icon: 'Y U NO-yuno.png' },
{ key: 'yawn', icon: 'Yawn-yawn.png' },
{ key: 'youdontsay', icon: 'You Don\'t Say-youdontsay-cage-uds.png' },
{ key: 'youthfulfear', icon: 'Youthful Fear-mommy-zomg.png' },
{ key: 'surprised', icon: 'surprised-surprised1-surprised.png' }
    ];
