var tmpl = '<div class="icon"><img src="../trollicons/$img" /></div>';
var icons = [
{ key: 'actuallyok', icon: 'Actually-actually-okay3.png' },
{ key: 'aintthatsomeshit', icon: 'Aint That Some Shit-celo-aintthatsomeshit.png' },
{ key: 'aliens', icon: 'Aliens-aliens.png' },
{ key: '', icon: 'All the things-allthethings.png' },
{ key: '', icon: 'Anti Joke Chicken-antichicken-antijokechicken.png' },
{ key: '', icon: 'Are You Kidding Me-areyoukiddingme-areyoukidding-stfu-areyoufuckingkiddingme.png' },
{ key: '', icon: 'Aw Man-awman-whyhands.png' },
{ key: '', icon: 'Aw-aw-why.png' },
{ key: '', icon: 'Awww Yea-awyea-awyeah-ay.png' },
{ key: '', icon: 'Bad Poker Face-badpokerface-badpoker.png' },
{ key: '', icon: 'Beer Guy-beerguy-beer.png' },
{ key: '', icon: 'Beh-beh.png' },
{ key: '', icon: 'Big Mouth High Face-bmhf-bigmouth.png' },
{ key: '', icon: 'Busted-busted-oops.png' },
{ key: '', icon: 'Canadian Rage-canadianrage-canadian.png' },
{ key: '', icon: 'Captain Obvious-captainobvious.png' },
{ key: '', icon: 'Cereal Guy Angry-cerealguyangry-cerealangry.png' },
{ key: '', icon: 'Cereal Guy Squint-cerealguysquint-cerealsquint.png' },
{ key: '', icon: 'Cereal Guy-cerealguy-cereal.png' },
{ key: '', icon: 'Cereal Spitting-cerealspit-spit.png' },
{ key: '', icon: 'Challenge Considered-challengeconsidered-considered.png' },
{ key: '', icon: 'Challenge-challenge.png' },
{ key: '', icon: 'Classy Fap-classyfap-richfap.png' },
{ key: '', icon: 'Clever Girl-clevergirl.png' },
{ key: '', icon: 'Close Enough-closeenough-ce.png' },
{ key: '', icon: 'Conflicting Emotions-notsure-dunno.png' },
{ key: '', icon: 'Confused-confused-butwhy.png' },
{ key: '', icon: 'Crazy Concentrate Sweat-sweat-workinghard.png' },
{ key: '', icon: 'Cry-cry-baw.png' },
{ key: '', icon: 'Dazed-dazed.png' },
{ key: '', icon: 'Desk flip-deskflip-flip-tableflip-desk-table.png' },
{ key: '', icon: 'Devil Troll-deviltroll-evil-devil.png' },
{ key: '', icon: 'Dog Sweet Jesus-dogsweetjesus.png' },
{ key: '', icon: 'Doge-doge.png' },
{ key: '', icon: 'Douchebag-dbag-brah-douche-douchebag.png' },
{ key: '', icon: 'Drool-drool.png' },
{ key: '', icon: 'Drunk-drunk.png' },
{ key: '', icon: 'Dude Come On Smile-comeon.png' },
{ key: '', icon: 'Dude-dude-meh.png' },
{ key: '', icon: 'Dumbfounded Kid-whoa-ooh.png' },
{ key: '', icon: 'Epic Fail Guy-epicfailguy-efg.png' },
{ key: '', icon: 'Errg-errg-release.png' },
{ key: '', icon: 'Everything Went Better Than Expected-everythingwentbetterthanexpected-betterthanexpected-ewbte.png' },
{ key: '', icon: 'Evil Smile-evilsmile-hah.png' },
{ key: '', icon: 'Excited-ya-yey.png' },
{ key: '', icon: 'Eyes-eyes-fff-imminent.png' },
{ key: '', icon: 'Faggot-Dog-faggotdog.png' },
{ key: '', icon: 'Fap Fap-fap-fapfap-fapfapfap.png' },
{ key: '', icon: 'Feel Like A Sir-likeasir.png' },
{ key: '', icon: 'Female Fap-femalefap-schlick.png' },
{ key: '', icon: 'Forever Alone Excited-foreveraloneexcited-faexcited-falaugh-friends.png' },
{ key: '', icon: 'Forever Alone-foreveralone-fa.png' },
{ key: '', icon: 'Foul Bachelor Frog-bachelorfrog-foulbachelorfrog-malefrog.png' },
{ key: '', icon: 'Foul Bachelorette Frog-bachelorettefrog-foulbachelorettefrog-femalefrog.png' },
{ key: '', icon: 'Freddie Mercury-freddie-hellyes.png' },
{ key: '', icon: 'Fry Not Sure If-notsureif.png' },
{ key: '', icon: 'Fry-fry-notsureiftrolling-nsit.png' },
{ key: '', icon: 'Fu Manchu-fumanchu.png' },
{ key: '', icon: 'Fuck That Shit Right-rightfuckthat-rft.png' },
{ key: '', icon: 'Fuck That Shit-fuckthatshit-fuckthat-ft-leftfuckthat-lft.png' },
{ key: '', icon: 'Fuck Yeah Words-fuckyeahwords-fywords.png' },
{ key: '', icon: 'Fuck Yeah-fuckyeah-fy.png' },
{ key: '', icon: 'Fuu-rage2-epicrage-fu2.png' },
{ key: '', icon: 'GTFO-gtfo.png' },
{ key: '', icon: 'Gah-gah-sweaty.png' },
{ key: '', icon: 'Gasp-gasp.png' },
{ key: '', icon: 'Gay Troll-gaytroll-gay.png' },
{ key: '', icon: 'Genius-genius-genious.png' },
{ key: '', icon: 'Gonna fuck that taco-taco.png' },
{ key: '', icon: 'Grandma Shit-grandmashit-shit.png' },
{ key: '', icon: 'Grandma-grandma-granny.png' },
{ key: '', icon: 'Granny Troll-grannytroll.png' },
{ key: '', icon: 'Grinch-grinch.png' },
{ key: '', icon: 'Gropaga-gropaga.png' },
{ key: '', icon: 'Grumpy Cat-grumpycat-grumpycatno.png' },
{ key: '', icon: 'Gun Left-lgun.png' },
{ key: '', icon: 'Gun Right-rgun.png' },
{ key: '', icon: 'Happy Face -happyface.png' },
{ key: '', icon: 'Happy-happy.png' },
{ key: '', icon: 'Haters Gonna Hate-hatersgonnahate-haters-hgh.png' },
{ key: '', icon: 'Heh heh-hehheh-hehehe.png' },
{ key: '', icon: 'Hehe Lizard-lizard.png' },
{ key: '', icon: 'Herp Derp-herpderp-herp-derp.png' },
{ key: '', icon: 'High Expectation Asian Dad-asiandad.png' },
{ key: '', icon: 'High-high.png' },
{ key: '', icon: 'Hipster Kitty-hipster-hipsterkitty-hk.png' },
{ key: '', icon: 'Hmm-hmm.png' },
{ key: '', icon: 'Homophobic Seal-seal-gayseal-gaay.png' },
{ key: '', icon: 'I Am Disappoint-son-disappoint.png' },
{ key: '', icon: 'I Dont Want to Live on This Planet Anymore-idontwannalive-farnsworth.png' },
{ key: '', icon: 'I Lied-ilied-wayevil.png' },
{ key: '', icon: 'I See-isee-iseewhatyoudidthere.png' },
{ key: '', icon: 'If you know what i mean-ifyouknowwhatimean-bean.png' },
{ key: '', icon: 'Insane Wolf-insanewolf-wolf.png' },
{ key: '', icon: 'It\'s Not Okay-itsnotokay-okay4.png' },
{ key: '', icon: 'It\'s Something-itssomething.png' },
{ key: '', icon: 'It\'s Time-itstime-serious-determined.png' },
{ key: '', icon: 'It\'s a Trap-trap-itsatrap.png' },
{ key: '', icon: 'LOL (No Text)-ooo.png' },
{ key: '', icon: 'LOL-lol-LOL.png' },
{ key: '', icon: 'Lame Pun Coon-lamepuncoon-lamepun-puncoon.png' },
{ key: '', icon: 'Look-look.png' },
{ key: '', icon: 'Me Gusta Mucho Creepy-creepymegusta-cmg-evilmegusta-emg.png' },
{ key: '', icon: 'Me Gusta Perfect-mgperfect-megustaperfect-mgp.png' },
{ key: '', icon: 'Me Gusta-bepistrollingyoubetter-megusta-mg.png' },
{ key: '', icon: 'Melvin Fuck Yeah-melvinfuckyeah-melvinfy-mfy.png' },
{ key: '', icon: 'Melvin-melvin.png' },
{ key: '', icon: 'Milk-milk.png' },
{ key: '', icon: 'Mom-mom.png' },
{ key: '', icon: 'Moonshot-moonshot-noway-shocked.png' },
{ key: '', icon: 'Mother Of God-motherofgod.png' },
{ key: '', icon: 'Newspaper Guy Tear-newspaperguytear-newspapertear-tear.png' },
{ key: '', icon: 'Newspaper Guy-newspaperguy-newspaper.png' },
{ key: '', icon: 'No Me Gusta-nmg-nomegusta.png' },
{ key: '', icon: 'No-no.png' },
{ key: '', icon: 'Not Bad Obama-notbadobama-notbad-obama.png' },
{ key: '', icon: 'Not Okay-notokay-bitter.png' },
{ key: '', icon: 'Nothing to do here-rocket-jetpack.png' },
{ key: '', icon: 'Numb-numb-fear-scared-depressed.png' },
{ key: '', icon: 'Occupied-working-busy-focus.png' },
{ key: '', icon: 'Oh God Right-rohgod-rgross-rwtf.png' },
{ key: '', icon: 'Oh God Why-ohgodwhy.png' },
{ key: '', icon: 'Oh God-ohgod-gross-wtf-lgross-lwtf.png' },
{ key: '', icon: 'Oh No-uh-ohno.png' },
{ key: '', icon: 'Ohhh Yes-ohyes.png' },
{ key: '', icon: 'Ok-ok-nice-great-thumb-thumbs.png' },
{ key: '', icon: 'Okay-okay.png' },
{ key: '', icon: 'Omg Run-omgrun-run.png' },
{ key: '', icon: 'Overjoyed-overjoyed-nowords-daww.png' },
{ key: '', icon: 'Paranoid Parrot-paranoid-parrot-paranoidparrot.png' },
{ key: '', icon: 'Perfect-perfect-biggrin.png' },
{ key: '', icon: 'Pffttchhchhh-pft2-expectant.png' },
{ key: '', icon: 'Pft-pft-lulz.png' },
{ key: '', icon: 'Philosoraptor-philosoraptor-raptor.png' },
{ key: '', icon: 'Picard Facepalm-facepalm-picard.png' },
{ key: '', icon: 'Pickle Time-pickletime-pickle.png' },
{ key: '', icon: 'Pig-pig-pigrage.png' },
{ key: '', icon: 'Pirate-pirate.png' },
{ key: '', icon: 'Poker Face Thick-thickpokerface-thickpoker-guilty.png' },
{ key: '', icon: 'Poker Face-pokerface-poker-pf.png' },
{ key: '', icon: 'Problem Guy-problemguy-okaytroll.png' },
{ key: '', icon: 'Puke Rainbows-pukerainbows-pukesrainbows-rainbows.png' },
{ key: '', icon: 'Rage Blank-blankrage.png' },
{ key: '', icon: 'Rage Classic-fu-rage.png' },
{ key: '', icon: 'Rage Extreme-extremerage-xrage.png' },
{ key: '', icon: 'Rage Happy-happyrage-hrage.png' },
{ key: '', icon: 'Rage Lion-ragelion.png' },
{ key: '', icon: 'Rage Nuclear-nuclearrage-nrage-fu3.png' },
{ key: '', icon: 'Rage Omega-omegarage-orage-fu4.png' },
{ key: '', icon: 'Rage Quiet-quietrage.png' },
{ key: '', icon: 'Retard Dog-retarddog-dog.png' },
{ key: '', icon: 'Retarded Girl-retardedgirl.png' },
{ key: '', icon: 'Rich Fu-richfu-rich-quite.png' },
{ key: '', icon: 'Sad Melvin-sadmelvin.png' },
{ key: '', icon: 'Sad Shadow-sadshadow-okay2.png' },
{ key: '', icon: 'Sad Troll-sadtroll.png' },
{ key: '', icon: 'Sad-sad.png' },
{ key: '', icon: 'Satisfied-satisfied-relief-ahh-ah.png' },
{ key: '', icon: 'Seriously Chan-jackie-chan.png' },
{ key: '', icon: 'Shaking-shaking.png' },
{ key: '', icon: 'Side Mouth-sidemouth-lefu.png' },
{ key: '', icon: 'Smile-smile-catsmile.png' },
{ key: '', icon: 'So Close-soclose.png' },
{ key: '', icon: 'So hardcore-hardcore-sohardcore.png' },
{ key: '', icon: 'Socially Awkward Penguin-penguin-awkwardpenguin-sociallyawkwardpenguin.png' },
{ key: '', icon: 'Son Me Gusta-sonmegusta-smg.png' },
{ key: '', icon: 'Spiderpman-subtle-nonchalant.png' },
{ key: '', icon: 'Stare-stare.png' },
{ key: '', icon: 'Straight-straight.png' },
{ key: '', icon: 'Success Kid-successkid-kid-success.png' },
{ key: '', icon: 'Surprised Wide Open Mouth-surprised3.png' },
{ key: '', icon: 'Sweet Jesus Face-sweetjesus-sj.png' },
{ key: '', icon: 'Tada left-ltada.png' },
{ key: '', icon: 'Tada-tada-rtada.png' },
{ key: '', icon: 'That Way-thatway.png' },
{ key: '', icon: 'The Fuck Female-gthefuck-gtf.png' },
{ key: '', icon: 'The Fuck-thefuck-tf.png' },
{ key: '', icon: 'The-More-You-Know-tmyk.png' },
{ key: '', icon: 'ThingsWentOkay-thingswentokay-wentokay.png' },
{ key: '', icon: 'Throw Up In Mouth-throwupinmouth-throwup-fullmouth.png' },
{ key: '', icon: 'Tongue-tongue.png' },
{ key: '', icon: 'Troll Dad Jump-trolldadjump-tdjump-tdj.png' },
{ key: '', icon: 'Troll Dad Monocle-trolldadmonocle-trolldadm-tdm.png' },
{ key: '', icon: 'Troll God-trollgod-god.png' },
{ key: '', icon: 'Troll Hot-trollhot-hottroll-babe.png' },
{ key: '', icon: 'Troll Insane-insanetroll-insane-excited.png' },
{ key: '', icon: 'Troll Lol-trolol-trollol-trolllol.png' },
{ key: '', icon: 'Troll peeking-peek-trollpeek.png' },
{ key: '', icon: 'Troll-troll-problem-umad.png' },
{ key: '', icon: 'TrollDad-trolldad.png' },
{ key: '', icon: 'Trollicons-trollicons.png' },
{ key: '', icon: 'True Story-truestory.png' },
{ key: '', icon: 'Uhm-uhm-mad.png' },
{ key: '', icon: 'WTF is this shit-picardwtf-wtfisthisshit.png' },
{ key: '', icon: 'Wah-wah-huh.png' },
{ key: '', icon: 'Wait-wait-awno.png' },
{ key: '', icon: 'Wat-wat-suspicious.png' },
{ key: '', icon: 'Watch out-badass-watchout-ndgt-neil.png' },
{ key: '', icon: 'What Have I done -whathaveidone-whid.png' },
{ key: '', icon: 'What Have You Done-whathaveyoudone-whyd-done.png' },
{ key: '', icon: 'What-concerned.png' },
{ key: '', icon: 'Win-win-epicwin.png' },
{ key: '', icon: 'Wizard-Guy-wizard.png' },
{ key: '', icon: 'Y U NO-yuno.png' },
{ key: '', icon: 'Yawn-yawn.png' },
{ key: '', icon: 'You Don\'t Say-youdontsay-cage-uds.png' },
{ key: '', icon: 'Youthful Fear-mommy-zomg.png' },
{ key: '', icon: 'surprised-surprised1-surprised.png' }
    ];

    var allTemplates = '';
    for (var idx = 0; idx < icons.length; idx++) {
        var icon = icons[idx].icon,
        mappedTmpl = tmpl.replace('$img', icon);
        allTemplates += mappedTmpl;
    }

    var ctr = document.getElementById('container')
    ctr.innerHTML = allTemplates;

    function sendToCampfire(idx) {
        var icon = icons[idx].key;
        chrome.tabs.executeScript({
            code: 'window.postMessage({ type: "trollicon", text: "' + icon + '" }, "*");'
        }, function() {
            window.close();
        });
    }

    var allIcons = document.getElementsByClassName('icon');

    for (var idx = 0; idx < allIcons.length; idx++) {
        var iconTag = allIcons[idx];
        var fn = function() {
            var _idx = idx;
            return function() {
                sendToCampfire(_idx);
            }
        }()
        iconTag.onclick = fn;
    }

